# Generated by Django 4.1 on 2024-03-31 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
            },
        ),
        migrations.CreateModel(
            name='GroupCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                ('number', models.IntegerField(default=1, verbose_name='Порядковый номер')),
            ],
            options={
                'verbose_name': 'Группа характеристик',
                'verbose_name_plural': 'Группы характеристик',
            },
        ),
        migrations.CreateModel(
            name='CharacteristicItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                ('price', models.FloatField(default=0, verbose_name='Стоимость')),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristic.characteristic', verbose_name='Характеристика')),
            ],
            options={
                'verbose_name': 'Элемент характеристики',
                'verbose_name_plural': 'Элементы характеристики',
            },
        ),
    ]
