# Generated by Django 4.1 on 2024-07-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characteristic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristic',
            name='title',
            field=models.CharField(max_length=128, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='characteristicgroup',
            name='title',
            field=models.CharField(max_length=128, unique=True, verbose_name='Название'),
        ),
    ]
