# Generated by Django 4.1 on 2024-07-26 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characteristic', '0003_executiontime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executiontime',
            name='title',
            field=models.CharField(max_length=128, unique=True, verbose_name='Количество рабочих дней'),
        ),
    ]
