# Generated by Django 4.1 on 2024-03-30 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characteristic', '0001_initial'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='product/images/', verbose_name='Изображение')),
                ('execution_time', models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Количество рабочих дней')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='ProductToCharacteristicItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0, verbose_name='Стоимость')),
                ('number', models.IntegerField(default=1, verbose_name='Порядковый номер')),
                ('characteristic_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristic.characteristicitem', verbose_name='Элемент характеристик')),
                ('group_characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristic.groupcharacteristic', verbose_name='Проект')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
