# Generated by Django 4.1 on 2024-07-25 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productformcombination',
            options={'verbose_name': 'Комбинация для формы продукта', 'verbose_name_plural': 'Комбинации для форм продуктов'},
        ),
    ]
