# Generated by Django 4.1 on 2024-03-30 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttocharacteristicitem',
            options={'verbose_name': 'Продукт к Характеристикам', 'verbose_name_plural': 'Продукты к Характеристикам'},
        ),
    ]
