# Generated by Django 4.1 on 2024-07-25 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characteristic', '0003_executiontime'),
        ('product', '0002_alter_productformcombination_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcharacteristiccombination',
            name='execution_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='characteristic.executiontime', verbose_name='Срок исполнения'),
        ),
        migrations.AlterField(
            model_name='productformcombination',
            name='execution_time',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='characteristic.executiontime', verbose_name='Срок исполнения'),
        ),
    ]
