# Generated by Django 4.1 on 2024-03-30 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characteristic', '0001_initial'),
        ('product', '0002_alter_producttocharacteristicitem_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductToCharacteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0, verbose_name='Стоимость')),
                ('number', models.IntegerField(default=1, verbose_name='Порядковый номер')),
                ('is_product', models.BooleanField(default=False, help_text='Если это продукт, то он будет отображаться как отдельная единица', verbose_name='Это продукт?')),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristic.characteristic', verbose_name='Характеристика')),
                ('group_characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristic.groupcharacteristic', verbose_name='Проект')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Продукт к Характеристикам',
                'verbose_name_plural': 'Продукты к Характеристикам',
            },
        ),
        migrations.DeleteModel(
            name='ProductToCharacteristicItem',
        ),
    ]
