# Generated by Django 4.1 on 2024-07-26 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productcharacteristiccombination_execution_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcharacteristiccombination',
            name='title',
            field=models.TextField(blank=True, default=None, max_length=128, null=True, verbose_name='Название'),
        ),
    ]
