# Generated by Django 4.1 on 2024-03-31 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_parent'),
        ('characteristic', '0001_initial'),
        ('product', '0003_producttocharacteristic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Основа продукта',
                'verbose_name_plural': 'Основы продуктов',
            },
        ),
        migrations.CreateModel(
            name='CharacteristicProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                ('number', models.IntegerField(default=1, verbose_name='Порядковый номер')),
                ('group_characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristic.groupcharacteristic', verbose_name='Группа характеристик')),
            ],
            options={
                'verbose_name': 'Характеристика продукта',
                'verbose_name_plural': 'Характеристики продуктов',
            },
        ),
        migrations.CreateModel(
            name='CharacteristicProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0, verbose_name='Стоимость')),
                ('number', models.IntegerField(default=1, verbose_name='Порядковый номер')),
                ('characteristic_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristic.characteristicitem', verbose_name='Элемент характеристики')),
                ('characteristic_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.characteristicproduct', verbose_name='Характеристика продукта')),
            ],
            options={
                'verbose_name': 'Характеристика продукта',
                'verbose_name_plural': 'Характеристики продуктов',
            },
        ),
        migrations.CreateModel(
            name='GroupProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                ('number', models.IntegerField(default=1, verbose_name='Порядковый номер')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.baseproduct', verbose_name='Основа продукта')),
            ],
            options={
                'verbose_name': 'Группа продукта',
                'verbose_name_plural': 'Группы продуктов',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='number',
            field=models.IntegerField(default=1, verbose_name='Порядковый номер'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Стоимость'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='execution_time',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Время работы'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/product/image/', verbose_name='Изображение'),
        ),
        migrations.DeleteModel(
            name='ProductToCharacteristic',
        ),
        migrations.AddField(
            model_name='characteristicproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Продукт'),
        ),
        migrations.AddField(
            model_name='product',
            name='group',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='product.groupproduct', verbose_name='Группа продукта'),
            preserve_default=False,
        ),
    ]
