# Generated by Django 4.1 on 2024-07-26 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_productcharacteristiccombination_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcharacteristiccombination',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Название'),
        ),
    ]
