# Generated by Django 4.1 on 2024-07-27 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_productcharacteristiccombination_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcharacteristiccombination',
            name='show_as_product',
            field=models.BooleanField(default=True, verbose_name='Отображать как продукт'),
        ),
    ]
