# Generated by Django 4.1 on 2024-07-27 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_productcharacteristiccombination_show_as_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productform',
            name='title_admin',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='Название'),
        ),
    ]
