# Generated by Django 4.1 on 2024-07-27 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_productform_title_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcharacteristiccombination',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/productCombination/image/', verbose_name='Изображение'),
        ),
    ]
