# Generated by Django 4.1 on 2024-07-27 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_productcharacteristiccombination_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product/image/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='productcharacteristiccombination',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='productCombination/image/', verbose_name='Изображение'),
        ),
    ]
