# Generated by Django 4.1 on 2024-09-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productformcombination',
            name='price',
            field=models.FloatField(default=0.0, verbose_name='Стоимость'),
        ),
    ]
