# Generated by Django 4.1 on 2024-09-28 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_productformcombination_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productformcombination',
            name='price',
            field=models.FloatField(default=None, null=True, verbose_name='Стоимость'),
        ),
    ]
