# Generated by Django 4.1 on 2024-10-03 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_productimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductImage',
            new_name='ProductCharacteristicCombinationImage',
        ),
        migrations.AlterModelOptions(
            name='productcharacteristiccombinationimage',
            options={'verbose_name': 'Изображения продуктов', 'verbose_name_plural': 'Изображения продуктов'},
        ),
        migrations.RemoveField(
            model_name='productcharacteristiccombinationimage',
            name='product',
        ),
        migrations.AddField(
            model_name='productcharacteristiccombinationimage',
            name='product_characteristic_combination',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.productcharacteristiccombination', verbose_name='Продукт'),
            preserve_default=False,
        ),
    ]
