# Generated by Django 4.1 on 2024-10-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_rename_productimage_productcharacteristiccombinationimage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcharacteristiccombination',
            name='image',
        ),
        migrations.AddField(
            model_name='productcharacteristiccombinationimage',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Это главное изображение?'),
        ),
    ]
