# Generated by Django 4.1 on 2024-07-25 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characteristic', '0001_initial'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/product/image/', verbose_name='Изображение')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='ProductForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Форма продукта',
                'verbose_name_plural': 'Формы продуктов',
            },
        ),
        migrations.CreateModel(
            name='ProductFormCombination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_time', models.CharField(max_length=16, verbose_name='Срок исполнения')),
                ('combination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristic.combination', verbose_name='Комбинация')),
                ('product_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productform', verbose_name='Форма продукта')),
            ],
            options={
                'verbose_name': 'Форма продукта',
                'verbose_name_plural': 'Формы продуктов',
            },
        ),
        migrations.CreateModel(
            name='ProductCharacteristicCombination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0.0, verbose_name='Стоимость')),
                ('execution_time', models.CharField(max_length=16, verbose_name='Срок исполнения')),
                ('combination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristic.combination', verbose_name='Комбинация')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Комбинация характеристик у продукта',
                'verbose_name_plural': 'Комбинации характеристик у продукта',
            },
        ),
        migrations.CreateModel(
            name='ProductAdditionalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                ('price', models.FloatField(default=0.0, verbose_name='Стоимость')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Дополнительная услуга у продукта',
                'verbose_name_plural': 'Дополнительные услуги у продуктов',
            },
        ),
    ]
