# Generated by Django 4.1 on 2024-07-25 06:08

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
            },
        ),
        migrations.CreateModel(
            name='CharacteristicGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Группа характеристик',
                'verbose_name_plural': 'Группы характеристик',
            },
        ),
        migrations.CreateModel(
            name='Combination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristic.characteristic', verbose_name='Характеристика')),
                ('characteristic_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristic.characteristicgroup', verbose_name='Группа')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='characteristic.combination')),
            ],
            options={
                'verbose_name': 'Комбинация характеристик',
                'verbose_name_plural': 'Комбинации характеристик',
            },
        ),
        migrations.AddField(
            model_name='characteristic',
            name='characteristic_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='characteristic.characteristicgroup', verbose_name='Группа'),
        ),
    ]
